# Generated by Django 5.2.8 on 2025-12-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('performer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('wallet', models.FloatField(default=0.0)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('transportation_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_loc', models.TextField()),
                ('departure_loc', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(default='fallback.png', upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'discount_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('discount_id', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('maximum_value', models.IntegerField(blank=True, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'lost_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lost_id', models.IntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='Still Lost', max_length=255)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='HasPerformer',
            fields=[
                ('pk', models.CompositePrimaryKey('performer', 'event', blank=True, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
                ('performer', models.ForeignKey(db_column='performer_id', on_delete=django.db.models.deletion.RESTRICT, to='api.performer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(through='api.HasPerformer', to='api.performer'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('name', models.TextField()),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ticket_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.tickettype')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('pk', models.CompositePrimaryKey('report_id', 'attendee', blank=True, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.IntegerField()),
                ('report_content', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('administrator', models.ForeignKey(blank=True, db_column='Adminstrator_Username', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to='api.user')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_reports', to='api.user')),
                ('owner', models.ForeignKey(blank=True, db_column='Owner_Username', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_date', models.DateField(blank=True, null=True)),
                ('attendee', models.ForeignKey(blank=True, db_column='Attendee_Username', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='received_messages', to='api.user')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_Username', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_status', models.CharField(blank=True, max_length=255, null=True)),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, related_name='friend_requests_sent', to='api.user')),
                ('owner', models.ForeignKey(db_column='Owner_Username', on_delete=django.db.models.deletion.RESTRICT, related_name='friend_requests_received', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_status', models.CharField(blank=True, max_length=255, null=True)),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, related_name='following', to='api.user')),
                ('owner', models.ForeignKey(db_column='Owner_Username', on_delete=django.db.models.deletion.RESTRICT, related_name='followers', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('pk', models.CompositePrimaryKey('feedback_id', 'attendee', blank=True, editable=False, primary_key=True, serialize=False)),
                ('feedback_id', models.IntegerField()),
                ('feedback_content', models.TextField()),
                ('feedback_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(db_column='owner_Username', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.user'),
        ),
        migrations.CreateModel(
            name='HasBus',
            fields=[
                ('pk', models.CompositePrimaryKey('transportation', 'event', blank=True, editable=False, primary_key=True, serialize=False)),
                ('number_assigned', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
                ('transportation', models.ForeignKey(db_column='Transportation_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='buses',
            field=models.ManyToManyField(through='api.HasBus', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, db_column='Location_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('pk', models.CompositePrimaryKey('attendee', 'event', blank=True, editable=False, primary_key=True, serialize=False)),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'attendee'), name='unique_ticket_per_type_per_attendee'),
        ),
    ]
