# Generated by Django 5.2.8 on 2025-12-14 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('performer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('wallet', models.FloatField(default=0.0)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('transportation_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(default='fallback.png', upload_to='uploads/photos/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='HasPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('performer', models.ForeignKey(db_column='performer_id', on_delete=django.db.models.deletion.RESTRICT, to='api.performer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='performers',
            field=models.ManyToManyField(through='api.HasPerformer', to='api.performer'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ticket_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='api.tickettype')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.RESTRICT, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_content', models.TextField()),
                ('status', models.CharField(choices=[('R', 'Resolved'), ('P', 'Pending')], max_length=1)),
                ('administrator', models.ForeignKey(blank=True, db_column='Adminstrator_Username', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to='api.user')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='api.user')),
                ('owner', models.ForeignKey(blank=True, db_column='Owner_Username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_date', models.DateField(blank=True, null=True)),
                ('attendee', models.ForeignKey(blank=True, db_column='Attendee_Username', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='received_messages', to='api.user')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_Username', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('B', 'Blocked')], default='P', max_length=1)),
                ('attendee1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='api.user')),
                ('attendee2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('B', 'Blocked')], default='P', max_length=1)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='following', to='api.user')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='followers', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_content', models.TextField()),
                ('feedback_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('attendee', models.ForeignKey(db_column='Attendee_Username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(db_column='owner_Username', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.user'),
        ),
        migrations.CreateModel(
            name='HasBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_assigned', models.IntegerField(blank=True, null=True)),
                ('departure_loc', models.TextField()),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('transportation', models.ForeignKey(db_column='Transportation_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='buses',
            field=models.ManyToManyField(through='api.HasBus', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, db_column='Location_Id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_id', models.CharField(max_length=25)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'discount_id'), name='unique_discount_per_event')],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('lost_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('L', 'Still lost'), ('F', 'Found')], default='L', max_length=1)),
                ('event', models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.RESTRICT, to='api.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'lost_id'), name='unique_lost_id_per_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='hasperformer',
            constraint=models.UniqueConstraint(fields=('performer', 'event'), name='unique_performer_per_event'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_per_event'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'attendee'), name='unique_ticket_per_type_per_attendee'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_id', 'attendee'), name='unique_report_id_per_attendee'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('attendee1', 'attendee2'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('attendee', 'organizer'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('feedback_id', 'attendee'), name='unique_feedback_id_per_attendee'),
        ),
        migrations.AddConstraint(
            model_name='hasbus',
            constraint=models.UniqueConstraint(fields=('transportation', 'event'), name='unique_bus_per_event'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('attendee', 'event'), name='unique_wishlist_item'),
        ),
    ]
