# Generated by Django 5.2.8 on 2025-12-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='start_date',
        ),
        migrations.AddField(
            model_name='venue',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
