# Generated by Django 5.2.8 on 2025-12-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasperformer',
            name='performer',
            field=models.ForeignKey(db_column='performer_id', on_delete=django.db.models.deletion.CASCADE, to='api.performer'),
        ),
    ]
