# Generated by Django 5.2.8 on 2025-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_choice',
            field=models.CharField(choices=[('A', 'Anyone'), ('F', 'Friends only'), ('P', 'Private')], default='F', max_length=1),
        ),
    ]
