# Generated by Django 5.2.8 on 2025-12-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hasperformer_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('attendee', 'Attendee')], max_length=20),
        ),
    ]
