# Generated by Django 5.2.8 on 2025-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_privacy_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_choice',
            field=models.CharField(choices=[('A', 'Anyone'), ('F', 'Friend/Follow'), ('P', 'Private')], default='F', max_length=1),
        ),
    ]
