# Generated by Django 5.2.8 on 2025-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='arrival_loc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='departure_loc',
        ),
        migrations.AddField(
            model_name='hasbus',
            name='departure_loc',
            field=models.TextField(default='abdallahelsaeed'),
            preserve_default=False,
        ),
    ]
