# Generated by Django 5.2.8 on 2025-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_venue_end_date_remove_venue_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
