# Generated by Django 5.2.8 on 2025-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_privacy_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='bus', max_length=64),
            preserve_default=False,
        ),
    ]
