# Generated by Django 5.2.8 on 2025-12-10 17:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tickettype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow_status',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend_status',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='owner',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('B', 'Blocked')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='friend',
            name='attendee1',
            field=models.ForeignKey(default=datetime.datetime(2025, 12, 10, 17, 50, 35, 997456, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='attendee2',
            field=models.ForeignKey(default='alex', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('B', 'Blocked')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maximum_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='following', to='api.user'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='followers', to='api.user'),
        ),
    ]
