# Generated by Django 5.2.8 on 2025-12-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_follow_follow_status_remove_friend_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_id',
            field=models.CharField(max_length=25),
        ),
    ]
