# Generated by Django 5.2.8 on 2025-12-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_message_date_alter_message_sender_type'),
        ('api', '0005_add_cascade_to_username_fks'),
    ]

    operations = [
    ]
