# Generated by Django 5.2.8 on 2025-12-10 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_discount_discount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='pk',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='pk',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pk',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attendee',
            field=models.ForeignKey(db_column='Attendee_Username', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='lost_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('L', 'Still lost'), ('F', 'Found')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='attendee',
            field=models.ForeignKey(db_column='Attendee_Username', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='api.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='Owner_Username', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='api.user'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('P', 'Pending')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('U', 'Attendee'), ('OP', 'Pending organizer'), ('OA', 'Active organizer'), ('A', 'Administrator')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('feedback_id', 'attendee'), name='unique_feedback_id_per_attendee'),
        ),
        migrations.AddConstraint(
            model_name='lostitem',
            constraint=models.UniqueConstraint(fields=('event', 'lost_id'), name='unique_lost_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_id', 'attendee'), name='unique_report_id_per_attendee'),
        ),
    ]
