# Generated by Django 5.2.8 on 2025-12-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251216_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='status',
        ),
    ]
