# Generated by Django 5.2.8 on 2025-12-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_feedback_pk_remove_lostitem_pk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='owner',
            new_name='organizer',
        ),
    ]
