# Generated by Django 5.2.8 on 2025-12-17 06:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_is_read'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- USER COUNT
            CREATE OR REPLACE PROCEDURE count_user(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_user;
            END;
            $$;

            -- ORGANIZER COUNT
            CREATE OR REPLACE PROCEDURE count_organizer(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_user where status='Organizer';
            END;
            $$;

            -- category COUNT
            CREATE OR REPLACE PROCEDURE count_category(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_category;
            END;
            $$;

            -- EVENT COUNT
            CREATE OR REPLACE PROCEDURE count_event(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_event;
            END;
            $$;

            -- VENUE COUNT
            CREATE OR REPLACE PROCEDURE count_venue(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_venue;
            END;
            $$;

            -- BUS COUNT
            CREATE OR REPLACE PROCEDURE count_bus(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_vehicle;
            END;
            $$;

            -- PERFORMER COUNT
            CREATE OR REPLACE PROCEDURE count_performer(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_performer;
            END;
            $$;

            -- BUS CAPACITY
            CREATE OR REPLACE PROCEDURE max_capacity_bus(OUT max_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MAX(capacity) INTO max_cap FROM api_vehicle;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE min_capacity_bus(OUT min_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MIN(capacity) INTO min_cap FROM api_vehicle;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE avg_capacity_bus(OUT avg_cap NUMERIC)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT AVG(capacity) INTO avg_cap FROM api_vehicle;
            END;
            $$;

            -- VENUE CAPACITY
            CREATE OR REPLACE PROCEDURE max_venue_cap(OUT max_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MAX(capacity) INTO max_cap FROM api_venue;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE min_venue_cap(OUT min_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MIN(capacity) INTO min_cap FROM api_venue;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE avg_venue_cap(OUT avg_cap NUMERIC)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT AVG(capacity) INTO avg_cap FROM api_venue;
            END;
            $$;
            """,
            reverse_sql="""
            DROP PROCEDURE IF EXISTS count_user;
            DROP PROCEDURE IF EXISTS count_organizer;
            DROP PROCEDURE IF EXISTS count_event;
            DROP PROCEDURE IF EXISTS count_venue;
            DROP PROCEDURE IF EXISTS count_bus;
            DROP PROCEDURE IF EXISTS count_performer;
            DROP PROCEDURE IF EXISTS max_capacity_bus;
            DROP PROCEDURE IF EXISTS min_capacity_bus;
            DROP PROCEDURE IF EXISTS avg_capacity_bus;
            DROP PROCEDURE IF EXISTS max_venue_cap;
            DROP PROCEDURE IF EXISTS min_venue_cap;
            DROP PROCEDURE IF EXISTS avg_venue_cap;
            """
        )
    ]