# Generated by Django 5.2.8 on 2025-12-17 06:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message_is_read'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- USER COUNT
            CREATE OR REPLACE PROCEDURE count_user(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_user;
            END;
            $$;

            -- ORGANIZER COUNT
            CREATE OR REPLACE PROCEDURE count_organizer(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_user where status='Organizer';
            END;
            $$;

            -- category COUNT
            CREATE OR REPLACE PROCEDURE count_category(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_category;
            END;
            $$;

            -- EVENT COUNT
            CREATE OR REPLACE PROCEDURE count_event(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_event;
            END;
            $$;

            -- VENUE COUNT
            CREATE OR REPLACE PROCEDURE count_venue(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_venue;
            END;
            $$;

            -- BUS COUNT
            CREATE OR REPLACE PROCEDURE count_bus(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_vehicle;
            END;
            $$;

            -- PERFORMER COUNT
            CREATE OR REPLACE PROCEDURE count_performer(OUT total INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT COUNT(*) INTO total FROM api_performer;
            END;
            $$;

            -- BUS CAPACITY
            CREATE OR REPLACE PROCEDURE max_capacity_bus(OUT max_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MAX(capacity) INTO max_cap FROM api_vehicle;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE min_capacity_bus(OUT min_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MIN(capacity) INTO min_cap FROM api_vehicle;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE avg_capacity_bus(OUT avg_cap NUMERIC)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT AVG(capacity) INTO avg_cap FROM api_vehicle;
            END;
            $$;

            -- VENUE CAPACITY
            CREATE OR REPLACE PROCEDURE max_venue_cap(OUT max_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MAX(capacity) INTO max_cap FROM api_venue;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE min_venue_cap(OUT min_cap INT)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT MIN(capacity) INTO min_cap FROM api_venue;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE avg_venue_cap(OUT avg_cap NUMERIC)
            LANGUAGE plpgsql
            AS $$
            BEGIN
                SELECT AVG(capacity) INTO avg_cap FROM api_venue;
            END;
            $$;

            CREATE OR REPLACE PROCEDURE get_venue_usage_report(result_cursor REFCURSOR)
            LANGUAGE plpgsql AS $$
            BEGIN
                OPEN result_cursor FOR
                SELECT 
                    v.name AS venue_name,
                    v.city,
                    COUNT(DISTINCT e.event_id) AS events_hosted,
                    SUM(t.quantity) AS tickets_sold,
                    COALESCE(SUM(t.quantity * tt.price), 0)::DOUBLE PRECISION AS revenue
                FROM api_venue v
                LEFT JOIN api_event e ON v.location_id = e."Location_Id"
                LEFT JOIN api_tickettype tt ON e.event_id = tt."Event_Id"
                LEFT JOIN api_ticket t ON tt.ticket_type_id = t.ticket_type_id
                GROUP BY v.location_id, v.name, v.city
                ORDER BY revenue DESC LIMIT 5;
            END;
            $$;
            CREATE OR REPLACE PROCEDURE get_organizer_leaderboard(result_cursor REFCURSOR)
            LANGUAGE plpgsql AS $$
            BEGIN
                OPEN result_cursor FOR
                SELECT 
                    u.username AS organizer,
                    COUNT(DISTINCT f.id) AS followers,
                    COUNT(DISTINCT e.event_id) AS events,
                    COALESCE(SUM(t.quantity * tt.price), 0)::DOUBLE PRECISION AS total_revenue
                FROM api_user u
                LEFT JOIN api_event e ON u.username = e."owner_Username"
                LEFT JOIN api_follow f ON u.username = f.organizer_id
                LEFT JOIN api_tickettype tt ON e.event_id = tt."Event_Id"
                LEFT JOIN api_ticket t ON tt.ticket_type_id = t.ticket_type_id
                GROUP BY u.username
                ORDER BY total_revenue DESC
                LIMIT 5;
            END;
            $$;
            """,
            reverse_sql="""
            DROP PROCEDURE IF EXISTS count_user;
            DROP PROCEDURE IF EXISTS count_organizer;
            DROP PROCEDURE IF EXISTS count_event;
            DROP PROCEDURE IF EXISTS count_venue;
            DROP PROCEDURE IF EXISTS count_bus;
            DROP PROCEDURE IF EXISTS count_performer;
            DROP PROCEDURE IF EXISTS max_capacity_bus;
            DROP PROCEDURE IF EXISTS min_capacity_bus;
            DROP PROCEDURE IF EXISTS avg_capacity_bus;
            DROP PROCEDURE IF EXISTS max_venue_cap;
            DROP PROCEDURE IF EXISTS min_venue_cap;
            DROP PROCEDURE IF EXISTS avg_venue_cap;
            DROP PROCEDURE IF EXISTS get_organizer_leaderboard;
            DROP PROCEDURE IF EXISTS get_venue_usage_report;
            """
        )
    ]