# Generated by Django 5.2.8 on 2025-12-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_procedures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
