# Generated by Django 5.2.8 on 2025-12-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(db_column='Event_id', on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(db_column='Event_id', on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
