# Generated by Django 5.2.8 on 2025-12-18 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_discount_event_alter_tickettype_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(db_column='Event_Id', on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
