# Generated by Django 5.2.8 on 2025-12-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_discount_event_alter_tickettype_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasbus',
            name='number_assigned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
