# Generated by Django 5.2.8 on 2025-12-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_hasbus_number_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='available',
        ),
    ]
